services:
  sm_mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - "3310:3306"
    volumes:
      - ./docker/mysql/database:/var/lib/mysql
      - ./www/logs/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: sm_db
      MYSQL_USER: sm_username
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - sm_network
    restart: always
  sm_sphinx:
    image: macbre/sphinxsearch:3.4.1
    ports:
      - "127.0.0.1:36307:36307" # bind to local interface only!
    volumes:
      - ./docker/sphinx/data/index:/opt/sphinx/index  # directory where sphinx will store index data
      - ./docker/sphinx/sphinx.conf:/opt/sphinx/conf/sphinx.conf  # SphinxSE configuration file
      - ./docker/sphinx/data/local:/usr/local
    mem_limit: 512m # match indexer.value from sphinx.conf
    links:
      - sm_mysql
  sm_php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./www/logs/php:/var/log/php
      - ./www/backend:/var/www
      - ./www/frontend:/var/www/frontend
    links:
      - sm_mysql
    networks:
      - sm_network
    restart: always
  sm_nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    networks:
      - sm_network
    depends_on:
      - sm_php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/backend:/var/www
networks:
  sm_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.100.38.0/24
